### ISSUE TITLE
[Enhancement]: Implement 'CustomPageReportMode' for Windows

### ISSUE THREAD

**Issue by TENX-S** [ThexXTURBOXx/catcher_2#17] opened 2024-01-06 12:18 UTC
### Description

I'm trying to run `example/lib/custom_report_mode_example.dart` on Windows. But when I click Generate error button, it complains about `flutter: [2024-01-06 20:09:26.589966 | Catcher 2 | WARNING] Instance of 'CustomPageReportMode' in not supported for windows platform`

### Minimal Reproduction

```sh
$ cd example
$ flutter run -d windows lib/custom_report_mode_example.dart
```

### Exception or Error

```sh
A Dart VM Service on Windows is available at: http://127.0.0.1:12282/9lnH_hzxI4A=/
The Flutter DevTools debugger and profiler on Windows is available at: http://127.0.0.1:9100?uri=http://127.0.0.1:12282/9lnH_hzxI4A=/
flutter: [2024-01-06 20:09:26.588597 | Catcher 2 | INFO] Setup localization lazily!
flutter: [2024-01-06 20:09:26.589966 | Catcher 2 | WARNING] Instance of 'CustomPageReportMode' in not supported for windows platform
```

### Expected Behaviour

According to this [table](https://github.com/ThexXTURBOXx/catcher_2/blob/master/platform_support.md), custom report mode is supported by all platforms.

### Screenshots

![bug](https://github.com/ThexXTURBOXx/catcher_2/assets/40336192/a2bdbb5b-a445-445d-95ff-62a00a3ef37e)

### Device

PC

### OS

Windows 11

### Flutter version

3.18.0-14.0.pre.31 • channel master

### catcher_2 version

master

### Checklist

- [X] I have read and followed the **entire** [README](https://github.com/ThexXTURBOXx/catcher_2/blob/master/README.md) and it has not provided the solution I need.
- [X] I have provided all the information I can.

**Comment by ThexXTURBOXx** [comment] 2024-01-06 12:20
This is not a bug, but actually a missing feature. I am open to any PRs wanting to implement this on Windows platform.

**Comment by TENX-S** [comment] 2024-01-06 12:29
I'm curious about the custom page report mode being a platform-specific feature. Could you please provide more details or explain it further?

**Comment by ThexXTURBOXx** [comment] 2024-01-06 12:52
I see what you are confused about now: `CustomPageReportMode` is just there to demonstrate how to use custom report modes. It purposely fails on Windows and MacOS because of its `getSupportedPlatforms()` implementation.
This is just to show how to disable specific platforms.
Hence, I will close this issue as not planned.

**Closed by ThexXTURBOXx** 2024-01-06 12:52 UTC
Labels: enhancement

**Comment by TENX-S** [comment] 2024-01-06 13:23
Thanks for your explanation. Add `PlatformType.Windows` to `getSupportedPlatforms` make it works.
